[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["forge-std/=lib/forge-std/src/", "Contract.sol=src/Contract.sol/"]
chain_id = 1
auto_detect_solc = false
solc_version = "0.5.10"
evm_version = "petersburg"
optimizer = true
optimizer_runs = 200
libraries = [
    "src/Contract.sol:SafeMath:0x071108ad85d7a766b41e0f5e5195537a8fc8e74d",
    "original.sol:SafeMath:0x071108ad85d7a766b41e0f5e5195537a8fc8e74d",
    "assert-fix.sol:SafeMath:0x071108ad85d7a766b41e0f5e5195537a8fc8e74d",
    "flattened_out.sol:SafeMath:0x071108ad85d7a766b41e0f5e5195537a8fc8e74d",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
