[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["forge-std/=lib/forge-std/src/", "contracts/interfaces=src/interfaces/", "contracts/SwaposV2Pair.sol=src/SwaposV2Pair.sol/", "contracts/libraries=src/libraries/", "contracts/SwaposV2ERC20.sol=src/SwaposV2ERC20.sol/"]
chain_id = 1
auto_detect_solc = false
solc_version = "0.5.16"
evm_version = "istanbul"
optimizer = false
optimizer_runs = 200
libraries = []

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
