[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["forge-std/=lib/forge-std/src/", "contracts/interfaces=src/interfaces/", "contracts/protocol=src/protocol/", "contracts/dependencies=src/dependencies/", "contracts/misc=src/misc/", "@balancer-labs=src/@balancer-labs/"]
chain_id = 1
auto_detect_solc = false
solc_version = "0.8.10"
evm_version = "london"
optimizer = true
optimizer_runs = 200
libraries = []

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
