[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["forge-std/=lib/forge-std/src/", "Contract.sol=src/Contract.sol/"]
chain_id = 1
auto_detect_solc = false
solc_version = "0.8.7"
evm_version = "london"
optimizer = false
optimizer_runs = 200
libraries = []

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
