[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["forge-std/=lib/forge-std/src/", "@openzeppelin=src/@openzeppelin/", "contracts/staking=src/staking/", "contracts/interfaces=src/interfaces/"]
chain_id = 1
auto_detect_solc = false
solc_version = "0.7.5"
evm_version = "istanbul"
use_literal_content = true
optimizer = false
optimizer_runs = 200
libraries = []

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
