[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["forge-std/=lib/forge-std/src/", "@openzeppelin=src/@openzeppelin/", "contracts/interfaces=src/interfaces/", "contracts/library=src/library/", "contracts/bridge=src/bridge/", "@pancakeswap=src/@pancakeswap/"]
chain_id = 1
auto_detect_solc = false
solc_version = "0.6.12"
evm_version = "istanbul"
optimizer = true
optimizer_runs = 200
libraries = []

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
