# This workflow will do a clean installation of node dependencies, cache/restore them,
# and run automated tests using jest.

name: Run Automated Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ConSol

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
          ref: main
          submodules: recursive

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './ConSol/package-lock.json'

    - name: Install solc-typed-ast
      run: |
        cd solc-typed-ast
        npm install

    - name: Install dependencies
      run: npm ci

    - name: Run automated tests
      run: npm run test
