# This workflow will do a clean installation of node dependencies, cache/restore them, 
# lint and format the source code and commit any changes.

# Lint errors that cannot be automatically fixed will result in a failure.

name: Lint and Format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: lint_format
  cancel-in-progress: true
  
jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ConSol

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
      with:
          fetch-depth: 0
          ref: main
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './ConSol/package-lock.json'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Lint and fix if possible
      run: npm run lint:fix
    
    - name: Format
      run: npm run format
    
    - name: Commit any changes due to lint and format
      uses: EndBug/add-and-commit@v7.2.1
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
        add: .
        author_name: GitHub Action
        message: changes by lint&format script
